export const dummyTickets = [
  {
    ticket_id: 1,
    ticket_item_description: "Request for Laptop Quotes",
    ticket_quantity: 5,
    ticket_specifications: "Dell XPS 15, 16GB RAM, 512GB SSD",
    ticket_status: "PENDING",
    ticket_created_by: "Bob Smith",
    ticket_assigned_to: "Alice Johnson",
    ticket_date_created: "2025-03-10",
    ticket_last_updated: "2025-03-11",
  },
  {
    ticket_id: 2,
    ticket_item_description: "Compare Office Chair Prices",
    ticket_quantity: 10,
    ticket_specifications: "Ergonomic mesh chairs with lumbar support",
    ticket_status: "APPROVED",
    ticket_created_by: "Sarah Lee",
    ticket_assigned_to: "David Brown",
    ticket_date_created: "2025-03-08",
    ticket_last_updated: "2025-03-09",
  },
  {
    ticket_id: 3,
    ticket_item_description: "Find Best Supplier for Monitors",
    ticket_quantity: 8,
    ticket_specifications: "27-inch, 144Hz, IPS display",
    ticket_status: "PENDING",
    ticket_created_by: "Tom Wilson",
    ticket_assigned_to: "Emily Davis",
    ticket_date_created: "2025-03-07",
    ticket_last_updated: "2025-03-07",
  },
  {
    ticket_id: 4,
    ticket_item_description: "Bulk Order for Keyboards",
    ticket_quantity: 50,
    ticket_specifications: "Mechanical, Cherry MX Brown switches",
    ticket_status: "APPROVED",
    ticket_created_by: "Olivia Martinez",
    ticket_assigned_to: "Michael Green",
    ticket_date_created: "2025-03-06",
    ticket_last_updated: "2025-03-08",
  },
  {
    ticket_id: 5,
    ticket_item_description: "Purchase Software Licenses",
    ticket_quantity: 20,
    ticket_specifications: "Adobe Creative Suite, 1-year subscription",
    ticket_status: "PENDING",
    ticket_created_by: "Liam Scott",
    ticket_assigned_to: "Rachel Adams",
    ticket_date_created: "2025-03-05",
    ticket_last_updated: "2025-03-06",
  },
  {
    ticket_id: 6,
    ticket_item_description: "Set Up New Workstations",
    ticket_quantity: 3,
    ticket_specifications: "Adjustable desks with dual-monitor arms",
    ticket_status: "APPROVED",
    ticket_created_by: "Emma Robinson",
    ticket_assigned_to: "James Carter",
    ticket_date_created: "2025-03-04",
    ticket_last_updated: "2025-03-05",
  },
  {
    ticket_id: 7,
    ticket_item_description: "Upgrade Network Infrastructure",
    ticket_quantity: 1,
    ticket_specifications: "New routers, firewalls, and switches",
    ticket_status: "IN PROGRESS",
    ticket_created_by: "Ethan Miller",
    ticket_assigned_to: "Sophia White",
    ticket_date_created: "2025-03-03",
    ticket_last_updated: "2025-03-04",
  },
  {
    ticket_id: 8,
    ticket_item_description: "Hire IT Support Staff",
    ticket_quantity: 2,
    ticket_specifications: "Level 2 IT Support Specialists",
    ticket_status: "PENDING",
    ticket_created_by: "Chloe Hall",
    ticket_assigned_to: "Daniel Walker",
    ticket_date_created: "2025-03-02",
    ticket_last_updated: "2025-03-03",
  },
  {
    ticket_id: 9,
    ticket_item_description: "Review Security Policies",
    ticket_quantity: 1,
    ticket_specifications: "Internal IT security policy review",
    ticket_status: "COMPLETED",
    ticket_created_by: "Benjamin King",
    ticket_assigned_to: "Olivia Lewis",
    ticket_date_created: "2025-03-01",
    ticket_last_updated: "2025-03-02",
  },
  {
    ticket_id: 10,
    ticket_item_description: "Order Office Stationery",
    ticket_quantity: 200,
    ticket_specifications: "Pens, notebooks, sticky notes, markers",
    ticket_status: "APPROVED",
    ticket_created_by: "Isabella Wright",
    ticket_assigned_to: "Jc Miguel Beltran",
    ticket_date_created: "2025-02-28",
    ticket_last_updated: "2025-03-01",
  },
  {
    ticket_id: 11,
    ticket_item_description: "Migrate to Cloud Storage",
    ticket_quantity: 1,
    ticket_specifications: "AWS S3 with security compliance",
    ticket_status: "IN PROGRESS",
    ticket_created_by: "Lucas Mitchell",
    ticket_assigned_to: "Evelyn Baker",
    ticket_date_created: "2025-02-27",
    ticket_last_updated: "2025-02-28",
  },
  {
    ticket_id: 12,
    ticket_item_description: "Install Security Cameras",
    ticket_quantity: 5,
    ticket_specifications: "4K CCTV cameras with night vision",
    ticket_status: "PENDING",
    ticket_created_by: "Madison Harris",
    ticket_assigned_to: "Jc Miguel Beltran",
    ticket_date_created: "2025-02-26",
    ticket_last_updated: "2025-02-27",
  },
  {
    ticket_id: 13,
    ticket_item_description: "Replace Old Printers",
    ticket_quantity: 3,
    ticket_specifications: "High-speed laser printers",
    ticket_status: "APPROVED",
    ticket_created_by: "Noah Perez",
    ticket_assigned_to: "Zoe Nelson",
    ticket_date_created: "2025-02-25",
    ticket_last_updated: "2025-02-26",
  },
  {
    ticket_id: 14,
    ticket_item_description: "Evaluate CRM Solutions",
    ticket_quantity: 1,
    ticket_specifications: "Enterprise-level CRM software",
    ticket_status: "IN PROGRESS",
    ticket_created_by: "Ava Edwards",
    ticket_assigned_to: "Logan Parker",
    ticket_date_created: "2025-02-24",
    ticket_last_updated: "2025-02-25",
  },
  {
    ticket_id: 15,
    ticket_item_description: "Upgrade Employee Laptops",
    ticket_quantity: 10,
    ticket_specifications: "MacBook Pro M2, 16GB RAM, 1TB SSD",
    ticket_status: "REJECTED",
    ticket_created_by: "Lily Thompson",
    ticket_assigned_to: "Harper Scott",
    ticket_date_created: "2025-02-23",
    ticket_last_updated: "2025-02-24",
  },
  {
    ticket_id: 16,
    ticket_item_description: "Upgrade Employee Laptops",
    ticket_quantity: 10,
    ticket_specifications: "MacBook Pro M2, 16GB RAM, 1TB SSD",
    ticket_status: "IN PROGRESS",
    ticket_created_by: "Lily Thompson",
    ticket_assigned_to: "Jc Miguel Beltran",
    ticket_date_created: "2025-02-22",
    ticket_last_updated: "2025-02-23",
  },
];
