export const dummyTickets = [
  {
    ticket_id: 1,
    title: "Request for Laptop Quotes",
    status: "PENDING",
    assigned_to: "Alice Johnson",
    created_by: "Bob Smith",
    description: "Need 5 new laptops for the team.",
  },
  {
    ticket_id: 2,
    title: "Compare Office Chair Prices",
    status: "APPROVED",
    assigned_to: "David Brown",
    created_by: "Sarah Lee",
    description: "Looking for ergonomic chairs for the office.",
  },
  {
    ticket_id: 3,
    title: "Find Best Supplier for Monitors",
    status: "PENDING",
    assigned_to: "Emily Davis",
    created_by: "Tom Wilson",
    description: "Searching for 27-inch monitors with high refresh rate.",
  },
  {
    ticket_id: 4,
    title: "Bulk Order for Keyboards",
    status: "APPROVED",
    assigned_to: "Michael Green",
    created_by: "Olivia Martinez",
    description: "Ordering 50 mechanical keyboards for developers.",
  },
  {
    ticket_id: 5,
    title: "Purchase Software Licenses",
    status: "PENDING",
    assigned_to: "Rachel Adams",
    created_by: "Liam Scott",
    description: "Need licenses for project management software.",
  },
  {
    ticket_id: 6,
    title: "Set Up New Workstations",
    status: "APPROVED",
    assigned_to: "James Carter",
    created_by: "Emma Robinson",
    description: "Arrange new workstations for remote employees.",
  },
  {
    ticket_id: 7,
    title: "Upgrade Network Infrastructure",
    status: "IN PROGRESS",
    assigned_to: "Sophia White",
    created_by: "Ethan Miller",
    description: "Improve office network speed and security.",
  },
  {
    ticket_id: 8,
    title: "Hire IT Support Staff",
    status: "PENDING",
    assigned_to: "Daniel Walker",
    created_by: "Chloe Hall",
    description: "Recruit 2 IT support staff for the help desk.",
  },
  {
    ticket_id: 9,
    title: "Review Security Policies",
    status: "COMPLETED",
    assigned_to: "Olivia Lewis",
    created_by: "Benjamin King",
    description: "Ensure compliance with company security standards.",
  },
  {
    ticket_id: 10,
    title: "Order Office Stationery",
    status: "APPROVED",
    assigned_to: "Mason Young",
    created_by: "Isabella Wright",
    description: "Restock pens, notebooks, and office supplies.",
  },
  {
    ticket_id: 11,
    title: "Migrate to Cloud Storage",
    status: "IN PROGRESS",
    assigned_to: "Evelyn Baker",
    created_by: "Lucas Mitchell",
    description:
      "Move company files to cloud storage for better accessibility.",
  },
  {
    ticket_id: 12,
    title: "Install Security Cameras",
    status: "PENDING",
    assigned_to: "Henry Rodriguez",
    created_by: "Madison Harris",
    description: "Install CCTV cameras in office premises for security.",
  },
  {
    ticket_id: 13,
    title: "Replace Old Printers",
    status: "APPROVED",
    assigned_to: "Zoe Nelson",
    created_by: "Noah Perez",
    description: "Purchase and install new office printers.",
  },
  {
    ticket_id: 14,
    title: "Evaluate CRM Solutions",
    status: "IN PROGRESS",
    assigned_to: "Logan Parker",
    created_by: "Ava Edwards",
    description: "Research CRM software for better customer management.",
  },
  {
    ticket_id: 15,
    title: "Upgrade Employee Laptops",
    status: "REJECTED",
    assigned_to: "Harper Scott",
    created_by: "Lily Thompson",
    description: "Upgrade outdated laptops with new models.",
  },
  {
    ticket_id: 16,
    title: "Upgrade Employee Laptops",
    status: "IN PROGRESS",
    assigned_to: "Jc Miguel Beltran",
    created_by: "Lily Thompson",
    description: "Upgrade outdated laptops with new models.",
  },
];
